# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y27nvNd2b4yAo7T3A0cTKwBOPQnLXrJZ
"""

import streamlit as st
import pandas as pd
import joblib

# -----------------------------
# Load Model
# -----------------------------
@st.cache_resource
def load_model():
    return joblib.load("bike_demand_xgb_tuned.pkl")

model = load_model()

# -----------------------------
# App Title
# -----------------------------
st.title("Bike Rental Demand Prediction")

st.write("Provide feature values to predict bike rental count.")

# -----------------------------
# Sidebar Inputs
# -----------------------------
st.sidebar.header("Input Features")

season = st.sidebar.selectbox(
    "Season",
    ["springer", "summer", "fall", "winter"]
)

yr = st.sidebar.selectbox(
    "Year",
    [2011.0, 2012.0]
)

mnth = st.sidebar.selectbox(
    "Month",
    ["Jan","Feb","Mar","Apr","May","Jun",
     "Jul","Aug","Sep","Oct","Nov","Dec"]
)

hr = st.sidebar.slider("Hour", 0, 23, 12)

holiday = st.sidebar.selectbox(
    "Holiday",
    ["No", "Yes"]
)

weekday = st.sidebar.slider("Weekday (0 = Sunday, 6 = Saturday)", 0, 6, 0)

workingday = st.sidebar.selectbox(
    "Working Day",
    ["No work", "Work"]
)

weathersit = st.sidebar.selectbox(
    "Weather Situation",
    ["Clear", "Mist", "Light Snow/Rain", "Heavy Rain/Snow"]
)

atemp = st.sidebar.slider("Feels Like Temperature", 0.0, 1.0, 0.5)

hum = st.sidebar.slider("Humidity", 0.0, 1.0, 0.5)

windspeed = st.sidebar.slider("Windspeed", 0.0, 1.0, 0.2)

# -----------------------------
# Create Input DataFrame
# -----------------------------
input_data = pd.DataFrame([{
    "season": season,
    "yr": yr,
    "mnth": mnth,
    "hr": hr,
    "holiday": holiday,
    "weekday": weekday,
    "workingday": workingday,
    "weathersit": weathersit,
    "atemp": atemp,
    "hum": hum,
    "windspeed": windspeed
}])

# -----------------------------
# Display Input
# -----------------------------
st.subheader("Input Data")
st.write(input_data)

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict"):

    prediction = model.predict(input_data)[0]

    st.subheader("Predicted Bike Count")
    st.write(int(prediction))