# -*- coding: utf-8 -*-
"""Bike_Rental_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKskqFdJsxj9lvWSIz8AXJ3Atvog1hr_
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/media/harsh/Workstation/Work_Space/Projects/Bike_rental_deployment/Dataset.csv')

df.head()

df = df.replace('?', np.nan)
df = df.apply(pd.to_numeric, errors='ignore')
df.head()

df.info()

df['yr'] = df['yr'].fillna(method='ffill')
df['mnth'] = df['mnth'].fillna(method='ffill')
df.info()

df = df.drop(['instant','dteday','temp','casual','registered'],axis=1)

df.head()

df.info()

month_map = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec'
}
df['mnth'] = df['mnth'].map(month_map)
df.head()

"""#ModelBuilding"""

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from xgboost import XGBRegressor
import joblib

X = df.drop(columns='cnt')
y = df['cnt']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False  # set True if not time-aware
)

num_cols = ['atemp','hum','windspeed','yr']
cat_cols = ['season','mnth','holiday','weekday','workingday','weathersit','hr']

preprocess = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler())
        ]), num_cols),

        ('cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore'))
        ]), cat_cols)
    ]
)

xgb_model = Pipeline([
    ('preprocess', preprocess),
    ('model', XGBRegressor(
        n_estimators=700,
        max_depth=4,
        learning_rate=0.1,
        subsample=0.9,
        colsample_bytree=0.8,
        objective='reg:squarederror',
        random_state=42
    ))
])

xgb_model.fit(X_train, y_train)

def evaluate(model, X_test, y_test):
    preds = model.predict(X_test)
    return {
        'MAE': mean_absolute_error(y_test, preds),
        'RMSE': np.sqrt(mean_squared_error(y_test, preds)),
        'R2': r2_score(y_test, preds)
    }

results = pd.DataFrame({
    'XGBoost': evaluate(xgb_model, X_test, y_test)
}).T

print(results)

joblib.dump(xgb_model, 'bike_demand_xgb_tuned.pkl')

xgb_model.named_steps['model'].feature_importances_